apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: strimzi-kafka-operator
  repository: https://strimzi.io/charts/
  version: 0.38.0
description: A Helm chart for Kubernetes
name: kafka-msg-chart
type: application
version: 0.1.0
