apiVersion: v1
kind: Service
metadata:
  name: cryptography-service
  namespace: cryptography
spec:
  type: NodePort
  selector:
    app: cryptography-deploy
  ports:
    - port: 8001
      targetPort: 8001
